### ISSUE TITLE
Dynamic slides not working

### ISSUE THREAD

**Issue by snc** [Lizhooh/preact-swiper#1]
It seems that one cannot use dynamic slides.

Basically I replaced

```
<div className='slide'>Slide 1</div>
<div className='slide'>Slide 2</div>
<div className='slide'>Slide 3</div>
```

with

```
{slides.map(slide => {
  return (
    <div key={slide.id} className='slide'>{slide.title}</div>
  );
})}
```

where `slides` is passed via `props` and looks like

```
[
  {id: 1, title: 'Slide 1'},
  {id: 2, title: 'Slide 2'},
  {id: 3, title: 'Slide 3'},
  {id: 4, title: 'Slide 4'}
]
```

The initial slides are working as expected, but when altering `slides` the new slide does not appear.

**Comment by Lizhooh** [comment]
Repair.
But after the update, the slide will appear magical things.
I think this is `swiper` bug.
